name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  AKS_CLUSTER: ${{ secrets.AKS_CLUSTER }}
  IMAGE_NAME: game-center

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER }}

      - name: Update Deployment YAML
        run: |
          sed "s|REPLACE_ME_IMAGE_NAME|$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}|g" Yaml/combined-game.yaml > deployment_final.yaml

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            deployment_final.yaml
          images: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
